### ISSUE TITLE
Subscriber does not receive values when `.subscribe(on: scheduler).receive(on: scheduler)` used with the TestScheduler

### ISSUE THREAD

**Issue by sergdort** [pointfreeco/combine-schedulers#74] opened 2023-02-08 12:33 UTC
**Describe the bug**

I looks like there is an issue where a subscriber does not receive values when test scheduler is used in combination with `subscribe(on:)` and `receive(on:)` operators.

**To Reproduce**

```swift
    @MainActor func test_stuck() async {
        let subject = PassthroughSubject<Int, Never>()
        let scheduler = DispatchQueue.test
        var values: [Int] = []
        
        let cancelable = subject
            .subscribe(on: scheduler)
            .receive(on: scheduler)
            .map { $0 * $0 }
            .receive(on: scheduler)
            .sink { value in values.append(value) }
        
        let valuesToSend = [0, 1, 2, 3, 4]
        
        for value in valuesToSend {
            subject.send(value)
        }
        await scheduler.run()
        XCTAssertEqual(values, [0, 1, 4, 9, 16])
    }
```

**Expected behavior**
The above test should pass

**Screenshots**
N/A

**Environment**
 - Xcode 13.4.1
 - Swift 5.6.1

**Comment by stephencelis** [comment] 2023-02-08 15:50
@sergdort I'm not sure this is a bug, but expected behavior in Combine. The behavior you're seeing I related to `subscribe(on:)`, not `receive(on:)`, and you can reproduce it without `receive(on:)` at all:

```swift
let subject = PassthroughSubject<Int, Never>()
let scheduler = DispatchQueue.test
var values: [Int] = []
var cancellables: Set<AnyCancellable> = []

subject
  .subscribe(on: scheduler)
  .map { $0 * $0 }
  .sink { value in values.append(value) }
  .store(in: &cancellables)

let valuesToSend = [0, 1, 2, 3, 4]

for value in valuesToSend {
  subject.send(value)
}
await scheduler.run()
XCTAssertEqual(values, [0, 1, 4, 9, 16]) // ❌ not equal to []
```

When you attach the subject to publisher with `subscribe(on:)`, a single unit of scheduled work is added to the test scheduler, blocking downstream subscribers from receiving the event till it is processed. This means that when you feed to subject a bunch of events, there's nothing that queues them up.

If you run the scheduler _before_ queuing the operations up, the test passes:

```diff
+await scheduler.run()
 for value in valuesToSend {
   subject.send(value)
 }
-await scheduler.run()
 XCTAssertEqual(values, [0, 1, 4, 9, 16]) // ✅
```

You can verify the behavior with something like [CombineExt](/CombineCommunity/CombineExt)'s `ReplaySubject`, which will replay the values that `PassthroughSubject` otherwise loses:

```diff
-let subject = PassthroughSubject<Int, Never>()
+let subject = ReplaySubject<Int, Never>(bufferSize: 3) // 5 to pass
 let scheduler = DispatchQueue.test
 var values: [Int] = []
 var cancellables: Set<AnyCancellable> = []

 subject
   .subscribe(on: scheduler)
   .map { $0 * $0 }
   .sink { value in values.append(value) }
   .store(in: &cancellables)

 let valuesToSend = [0, 1, 2, 3, 4]

 for value in valuesToSend {
   subject.send(value)
 }
 await scheduler.run()
 XCTAssertEqual(values, [0, 1, 4, 9, 16]) // ❌ not equal to [4, 9, 16]
```

For what it's worth, we think `TestScheduler` is only appropriate for testing time-based asynchrony from operations that actually wait, like delays and timers. For simple scheduling, like `receive(on:)`/`subscribe(on:)`, we recommend `ImmediateScheduler`, which will also allow the original test to pass.

**Comment by mbrandonw** [comment] 2023-02-08 15:56
I haven't fully grok'd what is going on, but you can reduce the failure quite a bit. It happens with just a single `subscribe(on:)` and no `async`:

```swift
func test_stuck() {
  let scheduler = DispatchQueue.test

  let subject = PassthroughSubject<Int, Never>()
  var values: [Int] = []
  subject
    .subscribe(on: scheduler)
    .sink { values.append($0) }
    .store(in: &self.cancellables)

  subject.send(2)
  scheduler.run()
  XCTAssertEqual(values, [2])
}
```

I'm stepping through the test scheduler code, and I can clearly see that the scheduled item is being executed here:

https://github.com/pointfreeco/combine-schedulers/blob/1a666ca8fd5d5ebb0d54d6189806d55de3a8930c/Sources/CombineSchedulers/TestScheduler.swift#L125

…yet the `sink` closure is never called. Very strange.

**Comment by mbrandonw** [comment] 2023-02-08 15:58
Looks like @stephencelis got to the bottom of it while I was typing that up!

**Comment by sergdort** [comment] 2023-02-09 11:10
Hm, I see thanks a lot @stephencelis and @mbrandonw !

The reason I thought that it was scheduler bug, is because few of our tests that use the combination of `subscribe(on:)` `receive(on:)` are stuck when we updated to the 0.50.0 but were passing on the older version that we were using (0.39.1).

Here is a simple test case that I was replicate to our internal logic and it gets stuck on 0.50.0 of TCA and passes on 0.39.1
I wonder what are your thoughts on this? Do you think it's a regression or just limitation of Combine.

For the moment the only work around that we found was to disable `subscribe(on:)` operator when running tests 🙈

```swift
    @MainActor
    func test_stuck() async {
        let subject = PassthroughSubject<Int, Never>()
        let scheduler = DispatchQueue.test
        var cancellables = [AnyCancellable]()
        
        struct State: Equatable {
            var count: Int = 0
        }
        
        enum Action: Equatable {
            case increment
            case start
            case stop
        }
        
        struct Environment {
            var incrementor: Effect<Int, Never>
            var scheduler: AnySchedulerOf<DispatchQueue>
        }
        
        /// This will produce ~1000 values per second
        scheduler.schedule(after: scheduler.now, interval: .milliseconds(1)) {
            subject.send(1)
        }
        .store(in: &cancellables)
        
        let store = TestStore(
            initialState: State(),
            reducer: AnyReducer<State, Action, Environment> { state, action, env in
                switch action {
                case .start:
                    return env.incrementor
                        .subscribe(on: env.scheduler) // removing this operator make the test go through 
                        .receive(on: env.scheduler)
                        .throttle(for: .milliseconds(1000 / 4), scheduler: env.scheduler, latest: true)
                        .eraseToEffect()
                        .map { _ in
                            Action.increment
                        }
                        .eraseToEffect()
                        .cancellable(id: "token", cancelInFlight: true)
                case .increment:
                    state.count += 1
                    return .none
                case .stop:
                    return Effect.cancel(id: "token")
                }
            },
            environment: Environment(
                incrementor: subject.eraseToEffect(),
                scheduler: scheduler.eraseToAnyScheduler()
            )
        )
        
        await store.send(.start)
        await scheduler.advance()
        await scheduler.advance(by: .seconds(1))
        await store.receive(.increment) {
            $0.count = 1
        }
        await store.receive(.increment) {
            $0.count = 2
        }
        await store.receive(.increment) {
            $0.count = 3
        }
        await store.receive(.increment) {
            $0.count = 4
        }
        await store.send(.stop)
        await scheduler.advance()
    }
```

**Comment by sergdort** [comment] 2023-02-09 13:22
Hi, guys! It seem to me I've found the problem. 
So when we send a `.start` the `TestStore` is awaiting for the `TestReducer` to receive the subscription [here](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/TestStore.swift#L1045)

```swift
    let task = self.store
      .send(.init(origin: .send(self.fromScopedAction(action)), file: file, line: line))
    await self.reducer.effectDidSubscribe.stream.first(where: { _ in true }) 
```
Which suppose to push the value into `effectDidSubscribe` stream upon the callback from  `handleEvents(receiveSubscription:` operator [here](https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/TestStore.swift#L2311). 

And here is where the `TestScheduler` comes in. When we apply the `receive(on:)` what happens under the hood in the TestScheduler is that we just [add](https://github.com/pointfreeco/combine-schedulers/blob/main/Sources/CombineSchedulers/TestScheduler.swift#L242) the action a callback into the array. But since there is no way to drain the scheduler we are ended up in the deadlock per se.

Looking at the old implementation I see that there was no TestReducer there and we were relying on `await Task.megaYield()` which I suppose would just return control and client would be able to drain the reducer.

**Comment by mbrandonw** [comment] 2023-02-18 15:55
Hi @sergdort, since you opened an issue on TCA and it does indeed look like a TCA issue rather than CombineSchedulers problem, I'm going to close this out. We do plan on looking at this sometime soon but we just haven't had a chance lately.

**Closed by mbrandonw** 2023-02-18 15:55 UTC
