### ISSUE TITLE
Compatibility with M1 macbook (arm64)

### ISSUE THREAD

**Issue by micHar** [pointfreeco/combine-schedulers#15] opened 2021-01-20 17:23 UTC
**Describe the bug**
I cannot build the tests on an M1 macbook. It seems to work fine on intel machine. 

The issue is that if I start with a clean project I get `No such module CombineSchedulers` in IDE where the `import CombineSchedulers` is and when building my tests - under `Compile Swift Source Files (arm64)` I also get the error `No such module CombineSchedulers`. 

If I build my app target first, the errors in IDE disappears. But then I proceed to building my tests and I get `No such module MYMODULE` under `Compile Swift Source Files (arm64)`.

**Expected behavior**
Test target should build and run tests.

**Environment**
 - Xcode 12.3
 - Swift 5.0

**Comment by gregdropletapp** [comment] 2021-03-01 13:40
BUMP

**Comment by stephencelis** [comment] 2021-03-01 14:16
We had a similar issue reported to swift-composable-architecture here: https://github.com/pointfreeco/swift-composable-architecture/issues/344

It turned out to not be a problem with the library but rather an issue with the project depending on it. Can you reproduce your issue in a brand new project with no other dependencies? If so, and if you have a fix, we'd gladly accept a PR!

**Comment by stephencelis** [comment] 2021-03-01 14:19
Ha, now that I think of it, swift-composable-architecture depends on combine-schedulers, and that folks have been able to run the sample apps just fine, so I'm inclined to think that this isn't a library problem here, as well. Would love to have information about solutions to this issue. @mbrandonw and I haven't upgraded to M1s yet so we don't yet have a way of trying to reproduce the problem.

**Comment by gregdropletapp** [comment] 2021-03-01 14:21
Thanks @stephencelis 
I've reviewed pointfreeco/swift-composable-architecture#344 and it can be the issue.
I've to set "excluded architectures": arm64 because of using firebase messaging framework.
And then targets which has that excluded are not able to run this framework. Adding "clean" utils target fix the issue.

**Comment by stephencelis** [comment] 2021-03-03 18:04
@micHar Given the discussion above I'm going to close this out, but if you think it's still a problem, please let us know!

**Closed by stephencelis** 2021-03-03 18:04 UTC

**Comment by micHar** [comment] 2021-03-03 18:24
I will try that, thanks for letting me know

**Comment by gregdropletapp** [comment] 2021-03-04 08:43
Just to mention.
No Architectures excluded Utils target is not the fix at the end.
When you will try to include this Utils inside your Carthage base target (App) you will get same error from Xcode.
I've end-up removing completely Carthage from the project and use 100% XCFrameworks & SPM.
Then everything is ok (after removing excluded architectures)
